### ISSUE TITLE
Tittle of scenarios 2 and 3

### ISSUE THREAD

**Issue by hchiapello** [IFB-ElixirFr/sandboxbioscenarios#17]
Scenario 2 and 3 should have 2 different title/names

**Comment by dputhier** [comment]
The introduction of linux_basics_session02  is "During this course, you will discover files and folders organization in Unix and learn some new Bash commands". 

The introduction of linux_basics_session02  is "During this course, you will learn how to manipulate files and directories.". 

So linux_basics_session02 could "Linux file system".

I will change it to "Linux file system" and we may discuss it later.

**Comment by dputhier** [comment]
"Unix file system"
