### ISSUE TITLE
[scenario 2] parent directory

### ISSUE THREAD

**Issue by hchiapello** [IFB-ElixirFr/sandboxbioscenarios#18]
Add a definition of a parent directory

**Comment by dputhier** [comment]
At the moment the is no reference to parent directory. Do you have a proposal ?

**Comment by hchiapello** [comment]
A parent directory refers to the directory above another directory. Every directory, except the root directory, lies beneath another directory. The higher directory is called the parent directory, and the lower directory is called a subdirectory
(merci google ;-)

**Comment by dputhier** [comment]
Yes :). But where do you want to introduce it in the tutorial :).

**Comment by dputhier** [comment]
Now linux_basics_session02/steps/step01.md indicates:

            Here, `/shared/data` indicates that we are currently located in the `data` directory which itself is contained in the `shared` directory. The `shared` directory is frequently refered as the **parent directory** of `data`.
