### ISSUE TITLE
[scenario 2] complete the definition of the cp command

### ISSUE THREAD

**Issue by hchiapello** [IFB-ElixirFr/sandboxbioscenarios#19]
complete this definition  “The cp (copy) command copies files or directories. It takes 2 paths as argument:” by adding  :"the paths may be absolute or relative paths or filenames or the current directory named with '.' "

**Comment by dputhier** [comment]
I have indicated:

              ## Copying files and directories

              The `cp` (**c**o**p**y) command copies files or directories. It takes 2 paths as argument. These paths may be absolute or relative paths or filenames or the current directory named with '.'
